# Site settings
name: Less Or More
email: 996529090@qq.com
author: kaka2634
url: http://www.kaka2634.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/kaka2634/
description: Actually, less is more!
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: kaka2634
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : kaka2634
    duoshuo:
        short_name : kaka2634
    disqus :
        short_name : kaka2634
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light