# Site settings
title: Kun's Blog
header-img: "img/elephant.jpg"
tagline: "say something"  
description: "Be better"  
baseurl: ""
url: "http://kunliublog.tk/"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "KunLiu"
  email: 996529090@qq.com
  bio: "mid or feed"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username: none
twitter_username: liukun2634 
github_username: kaka2634  
facebook_username: kun.liu.5099940
weibo_username: 3509237361
zhihu_username: liukun-21

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
#- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Beijing

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "KunLiu"
      header-img: "img/mountain.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : liukun
  disqus :
      short_name : none

# Analytics and webmaster tools stuff goes here
google_analytics: UA-87821158-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation